# docker-compose build app
# docker-compose up -d
# docker-compose exec app bash :
    # rm -rf vendor composer.lock
    # composer install
    # php artisan key:generate
version: "3.7"
services:
  app:
    build:
      args:
        user: vinh
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: shoppingcart
    container_name: shoppingcart-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - shoppingcart

  db:
    image: mysql:8.0
    container_name: shoppingcart-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: shoppingcart
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_PASSWORD: 123456
      MYSQL_USER: vinh
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - shoppingcart

  nginx:
    image: nginx:alpine
    container_name: shoppingcart-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - shoppingcart

networks:
  shoppingcart:
    driver: bridge